Remove _types suffix from Thrift Cargo package names
Summary:
This suffix was necessary prior to D54710352 because there used to be 2 distinct Thrift-generated packages and they needed to have different Cargo package names (`foo`, `foo_types`) in order to appear in the same Cargo workspace.

kuecks noticed failures like the following in `oss-eden-linux-getdeps-nosystem` since the above diff:

```lang=text,counterexample
error: failed to resolve patches for `https://github.com/facebook/fb303.git`

Caused by:
  patch for `fb303_core` in `https://github.com/facebook/fb303.git` failed to resolve

Caused by:
  The patch location `/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/fb303/fb303/thrift` does not appear to contain any packages matching the name `fb303_core`.
```

I suspect this is related to:

https://www.internalfb.com/code/fbsource/[07765f7b56438645403907f8f314b21961d1e522]/fbcode/opensource/fbcode_builder/manifests/fb303?lines=1-2%2C13-14

using the crate's name (`fb303_core`) instead of the Cargo package name (`fb303_core_types`).

The `_types` suffix is no longer needed. This diff removes them and hopefully resolves that failure.

Reviewed By: zertosh

Differential Revision: D54859971

fbshipit-source-id: 538e64122bc7b57158d47ab4c2685b7bbbe2e3a1