Let cargo handle its own git fetches
Summary:
Context: https://fb.workplace.com/groups/rust.foundation.team/posts/1613252192522755

In D43983384 it was observed that "Build rust-shed" fails in `oss-mononoke-linux-getdeps` if you vendor a particular commit from https://github.com/jimblandy/perf-event.git. See this job on V7 of that diff: https://www.internalfb.com/intern/sandcastle/job/18014399413710280/insights

```
    Updating git repository `https://github.com/jimblandy/perf-event.git`
error: failed to load source for dependency `perf-event`

Caused by:
  Unable to update https://github.com/jimblandy/perf-event.git?rev=f15d5fa9c82a59d6134ca706b047a6baa2c24e58

Caused by:
  revspec 'f15d5fa9c82a59d6134ca706b047a6baa2c24e58' not found; class=Reference (4); code=NotFound (-3)
```

In D44095532, I confirmed that without `git-fetch-with-cli = true` in getdeps the same code succeeds the "Build rust-shed" step.
https://www.internalfb.com/intern/sandcastle/job/906715711/insights

The only difference between V7 of krallin's diff and V1 of my working diff is:

```
$ hg diff -r 14b25d1e64dbbf6d627eb8243e2c9c9146ebb75f -r 5320eb7617dc4367184508058386020c5ea52eb7
 diff --git a/fbcode/opensource/fbcode_builder/getdeps/cargo.py b/fbcode/opensource/fbcode_builder/getdeps/cargo.py
 --- a/fbcode/opensource/fbcode_builder/getdeps/cargo.py
+++ b/fbcode/opensource/fbcode_builder/getdeps/cargo.py
@@ -45,6 +45,8 @@
         # Enable using nightly features with stable compiler
         env["RUSTC_BOOTSTRAP"] = "1"
         env["LIBZ_SYS_STATIC"] = "1"
+        cmd = ["cargo", "--version"]
+        self._run_cmd(cmd, cwd=self.workspace_dir(), env=env)
         cmd = [
             "cargo",
             operation,
@@ -88,9 +90,6 @@
 [build]
 target-dir = '''{}'''

-[net]
-git-fetch-with-cli = true
-
 [profile.dev]
 debug = false
 incremental = false
```

Ultimately I guess the `git` CLI on the Sandcastle host must be ancient/problematic because I tested that Cargo is able to handle the following Cargo.toml even with `[net] get-fetch-with-cli = true` in .cargo/config.toml, with both git 2.34.1 (on my devserver) and git 2.39.2 (on my laptop).

```
[package]
name = "repro"
version = "0.0.0"

[dependencies]
perf-event = { git = "https://github.com/jimblandy/perf-event.git", rev = "f15d5fa9c82a59d6134ca706b047a6baa2c24e58", version = "0.4" }
```

I don't know why `[net] git-fetch-with-cli = true` is being used by getdeps. It showed up 3 years ago in D19193954 with no discussion.

Reviewed By: zertosh

Differential Revision: D44098634

fbshipit-source-id: 41b3fd81ed0ce71c31ed8199fed7864215f7a485