Back out "cmake needs openssl"
Summary:
Original commit changeset: 2f869768f3a8

Original Phabricator Diff: D33432903 (https://github.com/facebook/fb303/commit/dab8800c892ac8f3f575fd9d71583b948b55bdf1)

The prior commit broke the open source build for Watchman:

```
Exception: project openssl has no builder for <getdeps.manifest.ManifestContext object at 0x7f053d23fe80>
```

Reviewed By: lnicco

Differential Revision: D33675540

fbshipit-source-id: cdf11a967a2234263e5713eaf2959ec9dc2b0e52